import Foundation

/// Ingredient density lookup — generated from `app/lib/ingredient-density.ts`.
/// Regenerate with `bun run ios:density`. Do not edit by hand.
enum IngredientDensity {
    private static let table: [String: Double] = IngredientDensityData.densities

    static func lookup(_ name: String) -> Double? {
        let key = normalize(name)
        return table[key]
    }

    static func convertWithDensity(
        quantity: Double,
        from: String,
        to: String,
        density: Double
    ) -> Double? {
        guard density > 0 else { return nil }
        guard let ml = volumeToMl(quantity, unit: from) else {
            if let grams = weightToGrams(quantity, unit: from),
               let targetMl = volumeToMl(1, unit: to) {
                let mlAmount = grams / density
                return mlAmount / targetMl
            }
            return nil
        }
        let grams = ml * density
        if let targetMl = volumeToMl(1, unit: to) {
            return grams / density / targetMl
        }
        if to == "g" { return grams }
        if to == "kg" { return grams / 1000 }
        return nil
    }

    private static func normalize(_ name: String) -> String {
        name.lowercased()
            .replacingOccurrences(of: "[^a-z0-9\\s]", with: " ", options: .regularExpression)
            .split(separator: " ")
            .filter { !$0.isEmpty }
            .joined(separator: " ")
    }

    private static func volumeToMl(_ quantity: Double, unit: String) -> Double? {
        UnitConversion.convert(quantity, from: unit, to: "ml")
    }

    private static func weightToGrams(_ quantity: Double, unit: String) -> Double? {
        UnitConversion.convert(quantity, from: unit, to: "g")
    }
}

enum IngredientDensityData {
    static let densities: [String: Double] = [
        "00 flour": 0.53,
        "active dry yeast": 0.5,
        "agave syrup": 1.4,
        "all purpose flour": 0.53,
        "allpurpose flour": 0.53,
        "almond butter": 0.98,
        "almond flour": 0.41,
        "almond meal": 0.41,
        "almond milk": 1,
        "ap flour": 0.53,
        "apple cider vinegar": 1,
        "apple sauce": 1,
        "applesauce": 1,
        "arborio rice": 0.85,
        "avocado mashed": 0.96,
        "baking powder": 0.9,
        "baking soda": 0.87,
        "banana mashed": 0.95,
        "basil dried": 0.25,
        "basmati rice": 0.85,
        "bbq sauce": 1.05,
        "beef stock": 1,
        "besan flour": 0.5,
        "bicarb soda": 0.87,
        "bicarbonate of soda": 0.87,
        "blue cheese crumbled": 0.5,
        "bread flour": 0.54,
        "breadcrumbs": 0.3,
        "broth": 1,
        "brown rice": 0.85,
        "brown sugar": 0.93,
        "buckwheat flour": 0.52,
        "bulgur": 0.6,
        "butter": 0.96,
        "buttermilk": 1.03,
        "cacao powder": 0.35,
        "cake flour": 0.48,
        "canned pumpkin": 1,
        "canola oil": 0.92,
        "cashews": 0.6,
        "caster sugar": 0.88,
        "cheddar cheese grated": 0.45,
        "chicken stock": 1,
        "chickpea flour": 0.5,
        "chili powder": 0.5,
        "chocolate chips": 0.6,
        "cinnamon": 0.56,
        "cocoa powder": 0.35,
        "coconut flour": 0.35,
        "coconut milk": 0.96,
        "coconut oil": 0.92,
        "coconut sugar": 0.85,
        "condensed milk": 1.3,
        "confectioners sugar": 0.51,
        "corn flour": 0.48,
        "corn starch": 0.38,
        "corn syrup": 1.36,
        "cornmeal": 0.55,
        "cornstarch": 0.38,
        "cottage cheese": 0.8,
        "couscous": 0.65,
        "cream": 1,
        "cream cheese": 0.98,
        "crushed tomatoes": 1.02,
        "cumin": 0.5,
        "dark brown sugar": 0.93,
        "dark chocolate chips": 0.6,
        "demerara sugar": 0.88,
        "desiccated coconut": 0.35,
        "dijon mustard": 1,
        "double cream": 1,
        "dried breadcrumbs": 0.25,
        "dried yeast": 0.5,
        "dutch cocoa": 0.35,
        "evaporated milk": 1.08,
        "feta cheese": 0.55,
        "flaked coconut": 0.3,
        "flaky salt": 0.9,
        "flour": 0.53,
        "fresh yeast": 0.65,
        "garlic powder": 0.5,
        "gelatin": 0.9,
        "gelatine": 0.9,
        "ghee": 0.96,
        "ginger powder": 0.5,
        "goat cheese": 0.55,
        "golden syrup": 1.38,
        "graham flour": 0.5,
        "granulated sugar": 0.85,
        "greek yogurt": 1.06,
        "grits": 0.55,
        "ground almonds": 0.43,
        "ground cinnamon": 0.56,
        "ground cumin": 0.5,
        "ground ginger": 0.5,
        "ground nutmeg": 0.5,
        "ground nuts": 0.5,
        "hazelnuts": 0.63,
        "heavy cream": 1,
        "honey": 1.44,
        "icing sugar": 0.51,
        "instant yeast": 0.6,
        "jasmine rice": 0.85,
        "ketchup": 1.05,
        "kosher salt": 1,
        "lard": 0.9,
        "lemon juice": 1.03,
        "light brown sugar": 0.9,
        "lime juice": 1.02,
        "maple sugar": 0.9,
        "maple syrup": 1.36,
        "margarine": 0.93,
        "mascarpone": 0.95,
        "mashed avocado": 0.96,
        "mashed banana": 0.95,
        "mayonnaise": 0.91,
        "milk": 1.03,
        "milk chocolate chips": 0.6,
        "molasses": 1.39,
        "mozzarella grated": 0.35,
        "muscovado sugar": 0.93,
        "mustard": 1,
        "nut meal": 0.45,
        "nutmeg": 0.5,
        "nuts": 0.6,
        "oat flour": 0.42,
        "oat milk": 1,
        "oatmeal": 0.35,
        "oats": 0.35,
        "olive oil": 0.92,
        "onion powder": 0.5,
        "orange juice": 1.04,
        "oregano": 0.25,
        "panko": 0.25,
        "paprika": 0.5,
        "parmesan cheese grated": 0.45,
        "parmesan grated": 0.45,
        "parsley dried": 0.25,
        "passata": 1.02,
        "pastry flour": 0.5,
        "peanut butter": 1,
        "peanuts": 0.6,
        "pecans": 0.55,
        "pecans chopped": 0.45,
        "pectin": 0.5,
        "pistachios": 0.56,
        "plain flour": 0.53,
        "plain yogurt": 1.03,
        "polenta": 0.7,
        "porridge oats": 0.35,
        "potato starch": 0.4,
        "powdered sugar": 0.51,
        "pumpkin puree": 1,
        "quick oats": 0.38,
        "quinoa": 0.72,
        "rapeseed oil": 0.92,
        "raw sugar": 0.88,
        "red wine": 0.99,
        "rice": 0.85,
        "rice flour": 0.5,
        "rice syrup": 1.36,
        "rice vinegar": 1,
        "ricotta": 0.52,
        "risotto rice": 0.85,
        "rolled oats": 0.35,
        "rye flour": 0.5,
        "salt": 1.2,
        "salted butter": 0.96,
        "sea salt": 1.2,
        "self raising flour": 0.53,
        "self rising flour": 0.53,
        "selfraising flour": 0.53,
        "semolina": 0.71,
        "semolina flour": 0.71,
        "sesame paste": 1,
        "shortening": 0.93,
        "shredded coconut": 0.32,
        "single cream": 0.98,
        "skim milk": 1.03,
        "sour cream": 1,
        "soy milk": 1.02,
        "soy sauce": 1.1,
        "spelt flour": 0.48,
        "steel cut oats": 0.4,
        "stock": 1,
        "strong bread flour": 0.54,
        "strong flour": 0.54,
        "sugar": 0.85,
        "sunflower oil": 0.92,
        "superfine sugar": 0.88,
        "sweet potato puree": 1,
        "sweetened condensed milk": 1.3,
        "table salt": 1.2,
        "tahini": 1,
        "tapioca starch": 0.38,
        "thyme dried": 0.25,
        "tomato paste": 1.1,
        "tomato puree": 1.02,
        "tomato sauce": 1.02,
        "turbinado sugar": 0.88,
        "turmeric": 0.5,
        "unsalted butter": 0.96,
        "vanilla essence": 0.88,
        "vanilla extract": 0.88,
        "vegetable oil": 0.92,
        "vegetable stock": 1,
        "vinegar": 1,
        "walnuts": 0.5,
        "walnuts chopped": 0.45,
        "water": 1,
        "white flour": 0.53,
        "white rice": 0.85,
        "white sugar": 0.85,
        "white vinegar": 1,
        "white wine": 0.99,
        "whole milk": 1.03,
        "whole wheat": 0.5,
        "whole wheat flour": 0.5,
        "wholemeal": 0.5,
        "wholemeal flour": 0.5,
        "wine": 0.99,
        "worcestershire sauce": 1.05,
        "yogurt": 1.03,
    ]
}
