/**
 * One-time backfill for base_quantity / base_unit columns.
 *
 * Input JSON via stdin:
 * {
 *   "cargo": [{ "id": "...", "name": "flour", "quantity": 1, "unit": "cup" }],
 *   "meal_ingredient": [{ "id": "...", "ingredientName": "flour", "quantity": 1, "unit": "cup" }],
 *   "supply_item": [{ "id": "...", "name": "milk", "quantity": 1, "unit": "l" }]
 * }
 *
 * Example:
 *   wrangler d1 execute ration-db --remote --json --command \
 *     "SELECT json_object('cargo', json_group_array(json_object('id', id, 'name', name, 'quantity', quantity, 'unit', unit))) FROM cargo" \
 *     | bun scripts/backfill-base-quantity.ts --batch-size=500 \
 *     > /tmp/backfill-base-quantity.sql
 *
 * Review the SQL, then:
 *   wrangler d1 execute ration-db --remote --file=/tmp/backfill-base-quantity.sql
 */
import { computeBaseFields } from "../app/lib/base-quantity";

const TABLES = ["cargo", "meal_ingredient", "supply_item"] as const;
type TableName = (typeof TABLES)[number];

type RowInput = {
	id?: unknown;
	name?: unknown;
	ingredientName?: unknown;
	ingredient_name?: unknown;
	quantity?: unknown;
	unit?: unknown;
};

type BackfillInput = Partial<Record<TableName, RowInput[]>>;

function parseBatchSize(): number {
	const raw = Bun.argv.find((arg) => arg.startsWith("--batch-size="));
	const parsed = raw ? Number(raw.split("=")[1]) : 500;
	if (!Number.isInteger(parsed) || parsed < 1 || parsed > 5000) {
		throw new Error("--batch-size must be an integer from 1 to 5000");
	}
	return parsed;
}

function escapeSqlString(value: string): string {
	return value.replaceAll("'", "''");
}

function rowName(row: RowInput): string {
	const value = row.name ?? row.ingredientName ?? row.ingredient_name;
	return typeof value === "string" ? value : "";
}

function normalizedRow(table: TableName, row: RowInput, index: number) {
	if (typeof row.id !== "string" || row.id.trim().length === 0) {
		throw new Error(`${table}[${index}] is missing string id`);
	}
	const quantity = Number(row.quantity);
	if (!Number.isFinite(quantity)) {
		throw new Error(`${table}[${index}] has invalid quantity`);
	}
	if (typeof row.unit !== "string" || row.unit.trim().length === 0) {
		throw new Error(`${table}[${index}] is missing string unit`);
	}
	return {
		id: row.id,
		name: rowName(row),
		quantity,
		unit: row.unit,
	};
}

function statementForRow(
	table: TableName,
	row: ReturnType<typeof normalizedRow>,
) {
	const base = computeBaseFields(row.quantity, row.unit, row.name);
	return [
		`UPDATE ${table}`,
		`SET base_quantity = ${base.baseQuantity}, base_unit = '${base.baseUnit}'`,
		`WHERE id = '${escapeSqlString(row.id)}';`,
	].join(" ");
}

function chunk<T>(items: T[], size: number): T[][] {
	const chunks: T[][] = [];
	for (let i = 0; i < items.length; i += size) {
		chunks.push(items.slice(i, i + size));
	}
	return chunks;
}

const input = await Bun.stdin.text();
if (!input.trim()) {
	await Bun.write(
		Bun.stderr,
		"Expected JSON on stdin with cargo, meal_ingredient, and/or supply_item arrays.\n",
	);
	process.exit(1);
}

const batchSize = parseBatchSize();
const parsed = JSON.parse(input) as BackfillInput;
const output: string[] = [
	"-- Generated by scripts/backfill-base-quantity.ts",
	"-- Review before applying to D1.",
];
let totalRows = 0;

for (const table of TABLES) {
	const rows = parsed[table] ?? [];
	if (!Array.isArray(rows) || rows.length === 0) continue;
	const statements = rows.map((row, index) =>
		statementForRow(table, normalizedRow(table, row, index)),
	);
	totalRows += statements.length;
	for (const [chunkIndex, statementChunk] of chunk(
		statements,
		batchSize,
	).entries()) {
		output.push(
			"",
			`-- ${table} chunk ${chunkIndex + 1}: ${statementChunk.length} rows`,
			...statementChunk,
		);
	}
}

output.push("", `-- Total backfill updates: ${totalRows}`);
await Bun.write(Bun.stdout, `${output.join("\n")}\n`);
